<script lang="ts">
	import type { PageProps } from './$types';
	import ProjectDetail from '$lib/features/projects/components/ProjectDetail.svelte';

	// PageProps is generated by SvelteKit from the folder name, so params.id is
	// typed as string, not string | undefined.
	// PageProps lo genera SvelteKit a partir del nombre de la carpeta, así que
	// params.id viene tipado como string, no string | undefined.
	let { params }: PageProps = $props();
</script>

<!-- {#key} forces a remount when the id changes. Without it SvelteKit reuses
     the component when navigating between two projects, and the detail would
     keep showing the previous one's payments.
     {#key} fuerza el remonte cuando cambia el id. Sin esto SvelteKit reutiliza
     el componente al navegar entre dos proyectos, y el detalle seguiría
     mostrando los pagos del anterior. -->
{#key params.id}
	<ProjectDetail id={params.id} />
{/key}
